#ifndef CONFIG_H
#define CONFIG_H

enum program_t {
    PROGRAM_SERVO_TEST,
    PROGRAM_SPIN_TEST,
    PROGRAM_PHASE_OUTPUT_TEST,
    PROGRAM_PRINT_DRV_FAULTS,
    PROGRAM_PRINT_INPUT_VOLTAGE,
    PROGRAM_PRINT_ENCODER,
    PROGRAM_CAN_SERVO,
    PROGRAM_SEND_CAN_ANGLE
};

#ifndef CONFIG_PROGRAM
#define CONFIG_PROGRAM PROGRAM_CAN_SERVO
#endif

#endif // CONFIG_H
